"use client";

import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, FileDown, FileSpreadsheet, FileText, FileType2, LayoutDashboard, Plus, RefreshCw, Search, Sparkles, Trash2 } from "lucide-react";
import { useApp } from "@/components/providers/AppProvider";
import { Markdown } from "@/components/ui/Markdown";
import { EmptyState, Field, Modal, SectionHeader, Spinner } from "@/components/ui/primitives";
import { cn, formatDateTime, relativeTime } from "@/lib/utils";
import { REPORT_TYPES, reportTypeLabel } from "@/lib/formats";
import { assistantUrl, reportPrompt } from "@/lib/deep-link";
import type { Report } from "@/lib/types";

type ReportSummary = Omit<Report, "markdown" | "sections" | "data"> & { preview: string | null };

export function ReportWorkspace({ initialReports }: { initialReports: ReportSummary[] }) {
  const { api, pushToast, activeProjectId } = useApp();
  const [reports, setReports] = useState<ReportSummary[]>(initialReports);
  const [search, setSearch] = useState("");
  const [type, setType] = useState("all");
  const [loading, setLoading] = useState(false);
  const [selected, setSelected] = useState<Report | null>(null);
  const [detailLoading, setDetailLoading] = useState(false);
  const [showNew, setShowNew] = useState(false);

  const reload = useCallback(async () => {
    setLoading(true);
    try {
      const query = new URLSearchParams({ limit: "200" });
      if (search) query.set("search", search);
      if (type !== "all") query.set("type", type);
      if (activeProjectId) query.set("projectId", activeProjectId);
      const data = await api<{ reports: ReportSummary[] }>(`/api/reports?${query.toString()}`);
      setReports(data.reports);
    } catch (error) {
      pushToast({ tone: "error", title: "Could not load reports", description: error instanceof Error ? error.message : undefined });
    } finally {
      setLoading(false);
    }
  }, [api, search, type, activeProjectId, pushToast]);

  useEffect(() => {
    const timer = setTimeout(() => void reload(), search ? 260 : 0);
    return () => clearTimeout(timer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [search, type, activeProjectId]);

  const open = async (report: ReportSummary) => {
    setDetailLoading(true);
    try {
      const data = await api<{ report: Report }>(`/api/reports/${report.id}`);
      setSelected(data.report);
    } catch (error) {
      pushToast({ tone: "error", title: "Could not open the report", description: error instanceof Error ? error.message : undefined });
    } finally {
      setDetailLoading(false);
    }
  };

  const setStatus = async (report: Report, status: "draft" | "final") => {
    try {
      const data = await api<{ report: Report }>(`/api/reports/${report.id}`, { method: "PATCH", json: { status } });
      setSelected(data.report);
      await reload();
      pushToast({ tone: "success", title: status === "final" ? "Marked as final" : "Moved back to draft" });
    } catch (error) {
      pushToast({ tone: "error", title: "Could not update the report", description: error instanceof Error ? error.message : undefined });
    }
  };

  const requestDelete = async (report: ReportSummary | Report) => {
    try {
      await api("/api/approvals", {
        method: "POST",
        json: {
          type: "delete_data",
          title: `Delete report "${report.title}"`,
          summary: "Deleting a generated report needs your approval.",
          payload: { entity: "report", id: report.id },
          riskLevel: "medium",
        },
      });
      pushToast({ tone: "warning", title: "Deletion needs approval", description: "Approve it in Settings → Approvals." });
    } catch (error) {
      pushToast({ tone: "error", title: "Could not request deletion", description: error instanceof Error ? error.message : undefined });
    }
  };

  return (
    <div className="mx-auto w-full max-w-[1400px] px-3 py-4 sm:px-5">
      <SectionHeader
        title="Reports"
        subtitle="Deliverables generated by the agent — market and lead research, competitor analysis, website audits, proposals and status reports. Export as PDF, DOCX, CSV or Markdown."
        actions={
          <>
            <button className="btn btn-sm" onClick={() => void reload()}>
              {loading ? <Spinner /> : <RefreshCw size={12} />} Refresh
            </button>
            <button className="btn btn-primary btn-sm" onClick={() => setShowNew(true)}>
              <Plus size={12} /> New report
            </button>
          </>
        }
      />

      <div className="mt-4 flex flex-col gap-2 sm:flex-row">
        <div className="relative min-w-[200px] flex-1">
          <Search size={13} className="absolute left-2.5 top-1/2 -translate-y-1/2 text-faint" />
          <input className="input pl-8" placeholder="Search reports…" value={search} onChange={(event) => setSearch(event.target.value)} />
        </div>
        <select className="select sm:w-56" value={type} onChange={(event) => setType(event.target.value)}>
          <option value="all">All types</option>
          {REPORT_TYPES.map((item) => (
            <option key={item.value} value={item.value}>
              {item.label}
            </option>
          ))}
        </select>
      </div>

      {reports.length === 0 ? (
        <div className="panel mt-3">
          <EmptyState
            icon={<LayoutDashboard size={18} />}
            title="No reports yet"
            description="Ask the assistant for a report and it will research, write it with sources and save it here with an executive summary."
            action={
              <button className="btn btn-primary btn-sm" onClick={() => setShowNew(true)}>
                <Sparkles size={12} /> Generate a report
              </button>
            }
          />
        </div>
      ) : (
        <div className="mt-3 grid gap-2 lg:grid-cols-2 xl:grid-cols-3">
          {reports.map((report) => (
            <button
              key={report.id}
              className="panel flex flex-col p-3.5 text-left transition-colors hover:border-[color:var(--color-line-strong)]"
              onClick={() => void open(report)}
            >
              <div className="flex items-start justify-between gap-2">
                <span className="chip chip-accent h-5 px-1.5">{reportTypeLabel(report.type)}</span>
                <span className={cn("chip h-5 px-1.5", report.status === "final" ? "chip-success" : "")}>{report.status}</span>
              </div>
              <p className="mt-2 line-clamp-2 text-[0.82rem] font-medium leading-snug text-ink">{report.title}</p>
              {report.preview || report.summary ? <p className="mt-1.5 line-clamp-3 text-[0.72rem] leading-snug text-muted">{report.summary || report.preview}</p> : null}
              <div className="mt-3 flex items-center gap-2 text-[0.66rem] text-faint">
                <span>{relativeTime(report.createdAt)}</span>
                {report.sources?.length ? <span>· {report.sources.length} sources</span> : null}
                <span className="ml-auto flex items-center gap-1 opacity-70">
                  <FileDown size={11} /> export
                </span>
              </div>
            </button>
          ))}
        </div>
      )}

      <Modal
        open={Boolean(selected) || detailLoading}
        onClose={() => setSelected(null)}
        title={selected?.title ?? "Loading report…"}
        description={selected ? `${reportTypeLabel(selected.type)} · ${formatDateTime(selected.createdAt)} · ${selected.status}` : ""}
        size="xl"
        footer={
          selected ? (
            <>
              <button className="btn btn-sm" onClick={() => void requestDelete(selected)}>
                <Trash2 size={12} /> Request deletion
              </button>
              <div className="ml-auto flex flex-wrap items-center gap-2">
                <button className="btn btn-sm" onClick={() => void setStatus(selected, selected.status === "final" ? "draft" : "final")}>
                  <CheckCircle2 size={12} /> {selected.status === "final" ? "Reopen as draft" : "Mark final"}
                </button>
                <a className="btn btn-sm" href={`/api/reports/${selected.id}/export?format=md`} target="_blank" rel="noreferrer">
                  <FileText size={12} /> MD
                </a>
                <a className="btn btn-sm" href={`/api/reports/${selected.id}/export?format=pdf`}>
                  <FileDown size={12} /> PDF
                </a>
                <a className="btn btn-sm" href={`/api/reports/${selected.id}/export?format=docx`}>
                  <FileType2 size={12} /> DOCX
                </a>
                <a className="btn btn-sm" href={`/api/reports/${selected.id}/export?format=csv`}>
                  <FileSpreadsheet size={12} /> CSV
                </a>
              </div>
            </>
          ) : null
        }
      >
        {selected ? (
          <div className="space-y-4">
            {selected.summary ? (
              <div className="rounded-xl border border-[color:var(--color-line)] bg-white/[0.02] px-3.5 py-3">
                <p className="mb-1 text-[0.62rem] uppercase tracking-[0.1em] text-faint">Executive summary</p>
                <p className="text-[0.8rem] leading-relaxed text-ink-soft">{selected.summary}</p>
              </div>
            ) : null}
            {selected.markdown ? (
              <Markdown className="text-[0.82rem]">{selected.markdown}</Markdown>
            ) : selected.sections?.length ? (
              <div className="space-y-4">
                {selected.sections.map((section) => (
                  <div key={section.heading}>
                    <p className="text-[0.82rem] font-medium text-ink">{section.heading}</p>
                    <p className="mt-1 whitespace-pre-wrap text-[0.8rem] leading-relaxed text-ink-soft">{section.body}</p>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-xs text-muted">This report has no stored body.</p>
            )}
            {selected.sources?.length ? (
              <div className="border-t border-[color:var(--color-line)] pt-3">
                <p className="mb-1.5 text-[0.62rem] uppercase tracking-[0.1em] text-faint">Sources</p>
                <ul className="space-y-1">
                  {selected.sources.map((source) => (
                    <li key={source.url}>
                      <a className="break-all text-[0.72rem] text-[#b8c6ff] hover:underline" href={source.url} target="_blank" rel="noreferrer noopener">
                        {source.title || source.url}
                      </a>
                    </li>
                  ))}
                </ul>
              </div>
            ) : null}
          </div>
        ) : (
          <p className="flex items-center gap-2 py-6 text-xs text-muted">
            <Spinner /> Loading report…
          </p>
        )}
      </Modal>

      <NewReportModal open={showNew} onClose={() => setShowNew(false)} />
    </div>
  );
}

function NewReportModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [type, setType] = useState<string>("market_research");
  const [subject, setSubject] = useState("");

  return (
    <Modal
      open={open}
      onClose={onClose}
      title="Generate a report"
      description="The agent researches first, then writes the report with an executive summary, findings, data, recommendations and sources."
      footer={
        <>
          <button className="btn btn-sm" onClick={onClose}>
            Cancel
          </button>
          <button className="btn btn-primary btn-sm" disabled={!subject.trim()} onClick={() => { window.location.href = assistantUrl(reportPrompt(type, subject.trim())); }}>
            <Sparkles size={12} /> Generate with the assistant
          </button>
        </>
      }
    >
      <div className="space-y-3">
        <Field label="Report type">
          <select className="select" value={type} onChange={(event) => setType(event.target.value)}>
            {REPORT_TYPES.map((item) => (
              <option key={item.value} value={item.value}>
                {item.label}
              </option>
            ))}
          </select>
        </Field>
        <Field label="Subject" hint="Be specific — the agent uses this to plan its research.">
          <textarea className="textarea" rows={3} value={subject} placeholder="e.g. the UK AI bookkeeping market for my LocalProof project" onChange={(event) => setSubject(event.target.value)} />
        </Field>
        <p className="text-[0.7rem] leading-relaxed text-faint">
          Report generation runs a full research pass with live tools, so it takes a minute or two. Nothing is sent anywhere — the report is saved to this workspace.
        </p>
      </div>
    </Modal>
  );
}
