/** Report exports: real PDF, DOCX, Markdown and CSV produced server-side. */
import type { Report } from "@/lib/types";
import { reportToPlainText } from "@/lib/repo/reports";

/** PDF standard fonts are Latin-1; strip anything they cannot encode. */
function latin1(value: string): string {
  return value
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[\u2013\u2014]/g, "-")
    .replace(/\u2026/g, "...")
    .replace(/[^\x09\x0A\x0D\x20-\x7E\xA0-\xFF]/g, "");
}

export async function reportToPdf(report: Report): Promise<Uint8Array> {
  const { PDFDocument, StandardFonts, rgb } = await import("pdf-lib");
  const pdf = await PDFDocument.create();
  pdf.setTitle(report.title);
  pdf.setAuthor("Haseeb AI");
  pdf.setSubject(report.type.replace(/_/g, " "));
  pdf.setCreationDate(new Date(report.createdAt));

  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const pageSize: [number, number] = [595.28, 841.89];
  const margin = 56;
  const maxWidth = pageSize[0] - margin * 2;

  let page = pdf.addPage(pageSize);
  let cursorY = pageSize[1] - margin;

  const newPageIfNeeded = (needed: number) => {
    if (cursorY - needed < margin) {
      page = pdf.addPage(pageSize);
      cursorY = pageSize[1] - margin;
    }
  };

  const wrap = (text: string, size: number, font: typeof regular): string[] => {
    const lines: string[] = [];
    for (const rawLine of text.split("\n")) {
      const clean = latin1(rawLine);
      if (!clean.trim()) {
        lines.push("");
        continue;
      }
      let current = "";
      for (const word of clean.split(/\s+/)) {
        const candidate = current ? `${current} ${word}` : word;
        if (font.widthOfTextAtSize(candidate, size) <= maxWidth) {
          current = candidate;
        } else {
          if (current) lines.push(current);
          current = word;
        }
      }
      if (current) lines.push(current);
    }
    return lines;
  };

  const write = (text: string, options: { size?: number; font?: typeof regular; color?: [number, number, number]; spacing?: number; indent?: number } = {}) => {
    const size = options.size ?? 10.5;
    const font = options.font ?? regular;
    const color = options.color ?? [0.1, 0.12, 0.16];
    const indent = options.indent ?? 0;
    for (const line of wrap(text, size, font)) {
      newPageIfNeeded(size + 6);
      page.drawText(line, {
        x: margin + indent,
        y: cursorY,
        size,
        font,
        color: rgb(color[0], color[1], color[2]),
      });
      cursorY -= size + 4.5;
    }
    cursorY -= options.spacing ?? 4;
  };

  write(report.title, { size: 20, font: bold, spacing: 6 });
  write(`Generated by Haseeb AI · ${new Date(report.createdAt).toUTCString()} · type: ${report.type.replace(/_/g, " ")}`, {
    size: 8.5,
    color: [0.45, 0.5, 0.58],
    spacing: 12,
  });

  if (report.summary) {
    write("Executive summary", { size: 13, font: bold, spacing: 2 });
    page.drawLine({ start: { x: margin, y: cursorY + 3 }, end: { x: pageSize[0] - margin, y: cursorY + 3 }, thickness: 0.5, color: rgb(0.85, 0.87, 0.9) });
    cursorY -= 8;
    write(report.summary, { spacing: 10 });
  }

  const sections = report.sections?.length
    ? report.sections
    : report.markdown
      ? [{ heading: "Document", body: report.markdown }]
      : [];

  for (const section of sections) {
    write(section.heading, { size: 13, font: bold, spacing: 2 });
    page.drawLine({ start: { x: margin, y: cursorY + 3 }, end: { x: pageSize[0] - margin, y: cursorY + 3 }, thickness: 0.5, color: rgb(0.85, 0.87, 0.9) });
    cursorY -= 8;
    write(section.body, { spacing: 10 });
  }

  if (report.sources.length) {
    write("Sources", { size: 13, font: bold, spacing: 2 });
    report.sources.forEach((source, index) => {
      write(`${index + 1}. ${source.title ? `${source.title} — ` : ""}${source.url}`, { size: 9, color: [0.25, 0.35, 0.6] });
    });
  }

  return pdf.save();
}

export async function reportToDocx(report: Report): Promise<Buffer> {
  const { Document, Packer, Paragraph, HeadingLevel, TextRun } = await import("docx");
  const children = [
    new Paragraph({ text: report.title, heading: HeadingLevel.TITLE }),
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated by Haseeb AI · ${new Date(report.createdAt).toUTCString()} · ${report.type.replace(/_/g, " ")}`,
          italics: true,
          size: 18,
          color: "6B7280",
        }),
      ],
    }),
  ];

  if (report.summary) {
    children.push(new Paragraph({ text: "Executive summary", heading: HeadingLevel.HEADING_1 }));
    for (const paragraph of report.summary.split(/\n{2,}/)) {
      children.push(new Paragraph({ text: paragraph }));
    }
  }

  const sections = report.sections ?? (report.markdown ? [{ heading: "Document", body: report.markdown }] : []);
  for (const section of sections) {
    children.push(new Paragraph({ text: section.heading, heading: HeadingLevel.HEADING_2 }));
    for (const block of section.body.split(/\n{2,}/)) {
      const lines = block.split("\n");
      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed) continue;
        if (/^[-*]\s+/.test(trimmed)) {
          children.push(new Paragraph({ text: trimmed.replace(/^[-*]\s+/, ""), bullet: { level: 0 } }));
        } else if (/^#{1,6}\s+/.test(trimmed)) {
          children.push(new Paragraph({ text: trimmed.replace(/^#+\s+/, ""), heading: HeadingLevel.HEADING_3 }));
        } else if (/^\|/.test(trimmed)) {
          children.push(new Paragraph({ text: trimmed, style: "TableText" }));
        } else {
          children.push(new Paragraph({ text: trimmed.replace(/\*\*(.+?)\*\*/g, "$1") }));
        }
      }
    }
  }

  if (report.sources.length) {
    children.push(new Paragraph({ text: "Sources", heading: HeadingLevel.HEADING_2 }));
    report.sources.forEach((source, index) => {
      children.push(new Paragraph({ text: `${index + 1}. ${source.title ? `${source.title} — ` : ""}${source.url}` }));
    });
  }

  const document = new Document({ sections: [{ children }] });
  return Buffer.from(await Packer.toBuffer(document));
}

export function toCsv(rows: Array<Record<string, unknown>>): string {
  if (rows.length === 0) return "";
  const columns = Array.from(new Set(rows.flatMap((row) => Object.keys(row))));
  const escape = (value: unknown) => {
    if (value === null || value === undefined) return "";
    const text = typeof value === "object" ? JSON.stringify(value) : String(value);
    return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
  };
  const lines = [columns.join(",")];
  for (const row of rows) {
    lines.push(columns.map((column) => escape(row[column])).join(","));
  }
  return lines.join("\n");
}

export function reportToMarkdown(report: Report): string {
  return reportToPlainText(report);
}
