#!/usr/bin/env node
/**
 * Writes the portable schema to db/schema.sql.
 *
 * `lib/db/schema-sql.ts` is the single source of truth; this script emits the
 * same statements as a reviewable SQL file to apply to production Postgres
 * (`psql "$DATABASE_URL" -f db/schema.sql`) or to inspect in a PR.
 *
 *   npm run db:schema
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { SCHEMA_STATEMENTS } from "../lib/db/schema-sql.ts";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const target = path.join(root, "db", "schema.sql");

const header = `-- Haseeb AI — database schema
-- Generated by \`npm run db:schema\` from lib/db/schema-sql.ts. Do not edit by hand.
--
-- Portable subset of SQL: TEXT/INTEGER/REAL columns, ISO-8601 UTC timestamps as
-- TEXT, JSON as TEXT, booleans as INTEGER 0/1. The same statements run on
-- PostgreSQL (production) and SQLite (local development).
--
-- Apply with:  psql "$DATABASE_URL" -f db/schema.sql
`;

const body = SCHEMA_STATEMENTS.map((statement) => `${statement.trim().replace(/;?$/, ";")}`).join("\n\n");

await mkdir(path.dirname(target), { recursive: true });
await writeFile(target, `${header}\n${body}\n`, "utf8");

console.log(`Wrote ${SCHEMA_STATEMENTS.length} statements to ${path.relative(root, target)}`);
